Task 1: Slicing 1D Arrays


In [2]:
import numpy as np
# Create a 1D array of integers
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Print the entire array
print(array_1d)

# Slice the array to obtain the first half of the elements
first_half = array_1d[:len(array_1d)//2]

# Slice the array to obtain the last three elements
last_three = array_1d[-3:]

# Slice the array to obtain every second element
every_second = array_1d[::2]

# Slice the array to obtain elements from index 2 to index 7
index_2_to_7 = array_1d[2:8]

# Print the sliced arrays obtained in steps 3, 4, 5, and 6
print(first_half)
print(last_three)
print(every_second)
print(index_2_to_7)


[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
[ 8  9 10]
[1 3 5 7 9]
[3 4 5 6 7 8]


Task 2: Slicing 2D Arrays


In [3]:
# Create a 2D array of integers
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the entire array
print(array_2d)

# Slice the array to obtain the first row
first_row = array_2d[0]

# Slice the array to obtain the last column
last_column = array_2d[:, -1]

# Slice the array to obtain a subarray consisting of the first two rows and last two columns
subarray_1 = array_2d[:2, -2:]

# Slice the array to obtain a subarray consisting of the last two rows and first two columns
subarray_2 = array_2d[-2:, :2]

# Print the sliced arrays obtained in steps 3, 4, 5, and 6
print(first_row)
print(last_column)
print(subarray_1)
print(subarray_2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[3 6 9]
[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


Task 3: Slicing 3D Arrays


In [4]:
# Create a 3D array of integers
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Print the entire array
print(array_3d)

# Slice the array to obtain the first 2D array (2D slice) along the third dimension
first_2d_slice = array_3d[0]

# Slice the array to obtain the second 2D array (2D slice) along the third dimension
second_2d_slice = array_3d[1]

# Slice the array to obtain a subarray consisting of the first two 2D arrays along the third dimension
subarray_1 = array_3d[:2]

# Slice the array to obtain a subarray consisting of the last two 2D arrays along the third dimension
subarray_2 = array_3d[-2:]

# Print the sliced arrays obtained in steps 3, 4, 5, and 6
print(first_2d_slice)
print(second_2d_slice)
print(subarray_1)
print(subarray_2)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Task 4: Slicing Higher Order Data


In [5]:
# Create a higher order data structure (e.g., a 4D array or a nested list)
higher_order_data = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

# Print the entire data structure
print(higher_order_data)

# Slice the data structure to obtain a substructure consisting of the first half along the first dimension
substructure_1 = higher_order_data[:higher_order_data.shape[0]//2]

# Slice the data structure to obtain a substructure consisting of the last element along the last dimension
substructure_2 = higher_order_data[..., -1]

# Slice the data structure to obtain a substructure consisting of every second element along the second dimension
substructure_3 = higher_order_data[:, ::2]

# Slice the data structure to obtain a substructure consisting of elements from index 2 to index 7 along the third dimension
substructure_4 = higher_order_data[..., 2:8]

# Print the sliced substructures obtained in steps 3, 4, 5, and 6
print(substructure_1)
print(substructure_2)
print(substructure_3)
print(substructure_4)


[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]
[[[[ 1  2]
   [ 3  4]]]


 [[[ 9 10]
   [11 12]]]]
[]
