# Lab 20 - Zain Ramzan

1. Find the dot product of two arrays of different dimensions. (Hint: Use matrix multiplication rule):


In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
dot_product = np.dot(a, b)
print(dot_product)


[32]


2. Stack two square matrix of 3 dimension vertically and horizontally:


In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
vertical_stack = np.vstack((a, b))
horizontal_stack = np.hstack((a, b))
print(vertical_stack)
print(horizontal_stack)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


3. Take sum of rows in 5x4 matrix which is generated randomly:


In [3]:
import numpy as np

matrix = np.random.rand(5, 4)
row_sum = np.sum(matrix, axis=1)
print(row_sum)


[3.35519447 2.39343455 2.42072468 2.09247723 2.7265038 ]


4. Take mean of each row and subtract it from respective column of random integer matrix of 4x4:


In [4]:
import numpy as np

matrix = np.random.randint(0, 10, (4, 4))
row_mean = np.mean(matrix, axis=1)
result = matrix - row_mean.reshape(-1, 1)
print(result)


[[ 4.   -1.   -4.    1.  ]
 [-2.   -2.   -2.    6.  ]
 [ 1.75 -2.25 -2.25  2.75]
 [ 2.5   0.5   1.5  -4.5 ]]


5. Compute euclidean distance between two numpy arrays:


In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
distance = np.linalg.norm(a - b)
print(distance)


5.196152422706632


6. Normalise matrix of 5x5 row-wise and column-wise:


In [6]:
import numpy as np

matrix = np.random.rand(5, 5)
row_norm = np.linalg.norm(matrix, axis=1)
column_norm = np.linalg.norm(matrix, axis=0)
row_normalised = matrix / row_norm.reshape(-1, 1)
column_normalised = matrix / column_norm.reshape(1, -1)
print(row_normalised)
print(column_normalised)


[[0.37805254 0.49392931 0.44629877 0.64336276 0.00344801]
 [0.55221277 0.34675148 0.56426503 0.07979142 0.50006276]
 [0.61858029 0.70701632 0.14266127 0.2348302  0.20491192]
 [0.3835865  0.45445095 0.64508651 0.46537378 0.11673206]
 [0.67711626 0.14828708 0.01945888 0.49343196 0.52504359]]
[[0.36360775 0.53011503 0.51394353 0.72719349 0.00530584]
 [0.46366224 0.3248912  0.56726653 0.07873441 0.67177458]
 [0.51182157 0.65279422 0.14133097 0.22834397 0.27126484]
 [0.3116349  0.41199708 0.62749385 0.44432196 0.15173183]
 [0.54196781 0.13244572 0.01864819 0.46414173 0.67237163]]


7. Program that generates random integer matrix of size 6x6 start value from 5 and stop value of 10 and replaces minimum value with zero and maximum value with 10:


In [7]:
import numpy as np

matrix = np.random.randint(5, 11, (6, 6))
min_value = np.min(matrix)
max_value = np.max(matrix)
matrix[matrix == min_value] = 0
matrix[matrix == max_value] = 10
print(matrix)


[[10  6  6  6  6  6]
 [ 0  7  6  8  0  7]
 [ 7  6  7  8  6 10]
 [ 0 10  8  9  7  0]
 [ 7  7  7  8  9  9]
 [ 0  6  8  6  8  9]]


8. Using genfromtxt() from numpy library get IRIS dataset which is in csv format https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data Calculate mean, median and standard deviation of first column. Last column consists of different species name. Find unique values in last column and their count:


In [9]:
import numpy as np

data = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", delimiter=",", usecols=(0, 4))
mean = np.mean(data[:, 0])
median = np.median(data[:, 0])
std = np.std(data[:, 0])
species, count = np.unique(data[:, 1], return_counts=True)
print("Mean:", mean)
print("Median:", median)
print("Standard deviation:"


SyntaxError: incomplete input (3297001814.py, line 10)